import {ImageRequireSource} from 'react-native';

interface ImageName {
  introBackground: ImageRequireSource;
  lightLogo: ImageRequireSource;
  walkthroughs: {
    frame01: ImageRequireSource;
    frame02: ImageRequireSource;
    frame03: ImageRequireSource;
    frame04: ImageRequireSource;
    frame05: ImageRequireSource;
    frame06: ImageRequireSource;
    frame07: ImageRequireSource;
    frame08: ImageRequireSource;
    frame09: ImageRequireSource;
    frame10: ImageRequireSource;
  };
  auth: {
    'sign-in-02': ImageRequireSource;
    'sign-in-03': ImageRequireSource;
    'sign-in-04': ImageRequireSource;
    'sign-up-01': ImageRequireSource;
    'sign-up-02': ImageRequireSource;
    'forgot-password': ImageRequireSource;
    verify: ImageRequireSource;
    kyc: ImageRequireSource;
    interest: ImageRequireSource;
    insta: ImageRequireSource;
    fb: ImageRequireSource;
    gg: ImageRequireSource;
    twitter: ImageRequireSource;
  };
  avatar: {
    'avatar-01': ImageRequireSource;
    'avatar-02': ImageRequireSource;
    'avatar-03': ImageRequireSource;
    'avatar-04': ImageRequireSource;
    'avatar-05': ImageRequireSource;
    'avatar-06': ImageRequireSource;
    'avatar-07': ImageRequireSource;
    'avatar-08': ImageRequireSource;
    'avatar-09': ImageRequireSource;
    'avatar-10': ImageRequireSource;
    'avatar-11': ImageRequireSource;
    'avatar-12': ImageRequireSource;
    'avatar-13': ImageRequireSource;
  };
  menu: {
    menu05: ImageRequireSource;
    menu07: ImageRequireSource;
    menu10: ImageRequireSource;
    menu11: ImageRequireSource;
  };
  profile: {
    'profile-01': ImageRequireSource;
    'profile-02': ImageRequireSource;
    'profile-03': ImageRequireSource;
    'profile-04': ImageRequireSource;
    'card-learn-01': ImageRequireSource;
    'card-learn-02': ImageRequireSource;
    'card-learn-03': ImageRequireSource;
    'card-learn-04': ImageRequireSource;
    'card-01': ImageRequireSource;
    'card-02': ImageRequireSource;
    'card-03': ImageRequireSource;
    'gym-01': ImageRequireSource;
    'gym-02': ImageRequireSource;
    'gym-03': ImageRequireSource;
    'gym-04': ImageRequireSource;
    'bg-04': ImageRequireSource;
  };
  news: {
    'news-01': ImageRequireSource;
    'news-02': ImageRequireSource;
    'news-03': ImageRequireSource;
    'news-04': ImageRequireSource;
    'news-05': ImageRequireSource;
    'news-06': ImageRequireSource;
    'news-07': ImageRequireSource;
    'news-08': ImageRequireSource;
    'news-09': ImageRequireSource;
    'news-10': ImageRequireSource;
    light: ImageRequireSource;
    'post-01': ImageRequireSource;
    'post-02': ImageRequireSource;
    'post-03': ImageRequireSource;
    'post-04': ImageRequireSource;
    'post-05': ImageRequireSource;
    'book-01': ImageRequireSource;
    'book-02': ImageRequireSource;
    'book-03': ImageRequireSource;
  };
  media: {
    plan: ImageRequireSource;
    music: ImageRequireSource;
    beat: ImageRequireSource;
    beat_white: ImageRequireSource;
    'song-01': ImageRequireSource;
    'song-02': ImageRequireSource;
    'song-03': ImageRequireSource;
    'song-04': ImageRequireSource;
    disk: ImageRequireSource;
    stream: ImageRequireSource;
  };
  static: {
    runner: ImageRequireSource;
    bitcoin: ImageRequireSource;
    ripper: ImageRequireSource;
    litecoin: ImageRequireSource;
    cardano: ImageRequireSource;
    binance: ImageRequireSource;
    byte: ImageRequireSource;
    graphic: ImageRequireSource;
    chart: ImageRequireSource;
  };
}
export const Images: ImageName = {
  introBackground: require('./img_intro_background.png'),
  lightLogo: require('./img_light_logo.png'),
  avatar: {
    'avatar-01': require('./avatar/img_avatar_profile_01.png'),
    'avatar-02': require('./avatar/img_avatar_02.png'),
    'avatar-03': require('./avatar/img_avatar_03.png'),
    'avatar-04': require('./avatar/img_avatar_04.png'),
    'avatar-05': require('./avatar/img_avatar_05.png'),
    'avatar-06': require('./avatar/img_avatar_06.png'),
    'avatar-07': require('./avatar/img_avatar_07.png'),
    'avatar-08': require('./avatar/img_avatar_08.png'),
    'avatar-09': require('./avatar/img_avatar_09.png'),
    'avatar-10': require('./avatar/img_avatar_10.png'),
    'avatar-11': require('./avatar/img_avatar_11.png'),
    'avatar-12': require('./avatar/img_avatar_12.png'),
    'avatar-13': require('./avatar/img_avatar_13.png'),
  },
  walkthroughs: {
    frame01: require('./walkthroughs/img_frame_01.png'),
    frame02: require('./walkthroughs/img_frame_02.png'),
    frame03: require('./walkthroughs/img_frame_03.png'),
    frame04: require('./walkthroughs/img_frame_04.png'),
    frame05: require('./walkthroughs/img_frame_05.png'),
    frame06: require('./walkthroughs/img_frame_06.png'),
    frame07: require('./walkthroughs/img_frame_07.png'),
    frame08: require('./walkthroughs/img_frame_08.png'),
    frame09: require('./walkthroughs/img_frame_09.png'),
    frame10: require('./walkthroughs/img_frame_10.png'),
  },
  auth: {
    'sign-in-02': require('./auth/img_sign_in_02.png'),
    'sign-in-03': require('./auth/img_sign_in_03.png'),
    'sign-in-04': require('./auth/img_sign_in_04.png'),
    'sign-up-01': require('./auth/img_sign_up.png'),
    'sign-up-02': require('./auth/img_sign_up_01.png'),
    'forgot-password': require('./auth/img_forgot_password.png'),
    verify: require('./auth/img_verify.png'),
    kyc: require('./auth/img_kyc.png'),
    interest: require('./auth/img_interest.png'),
    fb: require('./auth/img_fb.png'),
    gg: require('./auth/img_gg.png'),
    twitter: require('./auth/img_twitter.png'),
    insta: require('./auth/img_insta.png'),
  },
  menu: {
    menu05: require('./menu/img_menu_05.png'),
    menu07: require('./menu/img_menu_07.png'),
    menu10: require('./menu/img_menu_10.png'),
    menu11: require('./menu/img_menu_11.png'),
  },
  profile: {
    'profile-01': require('./profile/img_profile_01.png'),
    'profile-02': require('./profile/img_profile_02.png'),
    'profile-03': require('./profile/img_profile_03.png'),
    'profile-04': require('./profile/img_profile_05.png'),
    'card-learn-01': require('./profile/img_card-learn-01.png'),
    'card-learn-02': require('./profile/img_card-learn-02.png'),
    'card-learn-03': require('./profile/img_card-learn-03.png'),
    'card-learn-04': require('./profile/img_card-learn-04.png'),
    'card-01': require('./profile/img_card_01.png'),
    'card-02': require('./profile/img_card_02.png'),
    'card-03': require('./profile/img_card_03.png'),
    'gym-01': require('./profile/gym_01.png'),
    'gym-02': require('./profile/gym_02.png'),
    'gym-03': require('./profile/gym_03.png'),
    'gym-04': require('./profile/gym_04.png'),
    'bg-04': require('./profile/img_bg_04.png'),
  },
  news: {
    'news-01': require('./news/img_news_01.png'),
    'news-02': require('./news/img_news_02.png'),
    'news-03': require('./news/img_news_03.png'),
    'news-04': require('./news/img_news_04.png'),
    'news-05': require('./news/img_news_05.png'),
    'news-06': require('./news/img_news_06.png'),
    'news-07': require('./news/img_news_07.png'),
    'news-08': require('./news/img_news_08.png'),
    'news-09': require('./news/img_news_09.png'),
    'news-10': require('./news/img_news_10.png'),
    light: require('./news/img_light.png'),
    'post-01': require('./news/img_post_01.png'),
    'post-02': require('./news/img_post_02.png'),
    'post-03': require('./news/img_post_03.png'),
    'post-04': require('./news/img_post_04.png'),
    'post-05': require('./news/img_post_05.png'),
    'book-01': require('./news/img_book_01.png'),
    'book-02': require('./news/img_book_02.png'),
    'book-03': require('./news/img_book_03.png'),
  },
  media: {
    plan: require('./media/img_plan_01.png'),
    music: require('./media/img_music.png'),
    beat: require('./media/img_beat.png'),
    beat_white: require('./media/img_beat_white.png'),
    'song-01': require('./media/img_song_01.png'),
    'song-02': require('./media/img_song_02.png'),
    'song-03': require('./media/img_song_03.png'),
    'song-04': require('./media/img_song_04.png'),
    disk: require('./media/img_disk.png'),
    stream: require('./media/img_stream.png'),
  },
  static: {
    runner: require('./static/img_runner.png'),
    graphic: require('./static/img_graphic.png'),
    bitcoin: require('./static/img_bitcoin.png'),
    ripper: require('./static/img_ripper.png'),
    litecoin: require('./static/img_litecoin.png'),
    cardano: require('./static/img_cardano.png'),
    binance: require('./static/img_binance.png'),
    byte: require('./static/img_byte.png'),
    chart: require('./static/img_chart_01.png'),
  },
};
