import {ImageRequireSource} from 'react-native';

export interface IconName {
  fb: ImageRequireSource;
  logo: ImageRequireSource;
  'arrow-back': ImageRequireSource;
  google: ImageRequireSource;
  apple: ImageRequireSource;
  location: ImageRequireSource;
  'left-play': ImageRequireSource;
  'right-play': ImageRequireSource;
  eye: ImageRequireSource;
  'close-eye': ImageRequireSource;
  'face-id': ImageRequireSource;
  'arrow-left': ImageRequireSource;
  'arrow-right': ImageRequireSource;
  user: ImageRequireSource;
  email: ImageRequireSource;
  lock: ImageRequireSource;
  close: ImageRequireSource;
  cc: ImageRequireSource;
  passport: ImageRequireSource;
  home: ImageRequireSource;
  settings: ImageRequireSource;
  bag: ImageRequireSource;
  message: ImageRequireSource;
  flame: ImageRequireSource;
  logout: ImageRequireSource;
  search: ImageRequireSource;
  more: ImageRequireSource;
  'face-detection': ImageRequireSource;
  'shape-close': ImageRequireSource;
  'white-logo': ImageRequireSource;
  'arrow-top': ImageRequireSource;
  arrow_right: ImageRequireSource;
  home_menu: ImageRequireSource;
  message_menu: ImageRequireSource;
  profile_menu: ImageRequireSource;
  settings_menu: ImageRequireSource;
  logout_menu: ImageRequireSource;
  portfolios: ImageRequireSource;
  page: ImageRequireSource;
  features: ImageRequireSource;
  portfolios_menu: ImageRequireSource;
  short_code: ImageRequireSource;
  extra_shop: ImageRequireSource;
  twitter: ImageRequireSource;
  instagram: ImageRequireSource;
  'outline-setting': ImageRequireSource;
  notification: ImageRequireSource;
  information: ImageRequireSource;
  'warning-mess': ImageRequireSource;
  phone: ImageRequireSource;
  option: ImageRequireSource;
  wishlist: ImageRequireSource;
  order: ImageRequireSource;
  'small-location': ImageRequireSource;
  'credit-card': ImageRequireSource;
  profile: ImageRequireSource;
  heart: ImageRequireSource;
  filter: ImageRequireSource;
  searchBottom: ImageRequireSource;
  call: ImageRequireSource;
  mess: ImageRequireSource;
  award: ImageRequireSource;
  stethoscope: ImageRequireSource;
  personal: ImageRequireSource;
  burn: ImageRequireSource;
  combined: ImageRequireSource;
  tree: ImageRequireSource;
  medicine: ImageRequireSource;
  doctor: ImageRequireSource;
  bookmark: ImageRequireSource;
  car: ImageRequireSource;
  health: ImageRequireSource;
  travel: ImageRequireSource;
  food: ImageRequireSource;
  drink: ImageRequireSource;
  ladder: ImageRequireSource;
  upload: ImageRequireSource;
  rewind: ImageRequireSource;
  forward: ImageRequireSource;
  play: ImageRequireSource;
  repeat: ImageRequireSource;
  pause: ImageRequireSource;
  shuffle: ImageRequireSource;
  smile: ImageRequireSource;
  share: ImageRequireSource;
  edit: ImageRequireSource;
  glueco: ImageRequireSource;
  weight: ImageRequireSource;
  'bookmark-outline': ImageRequireSource;
  'cup-of-tea': ImageRequireSource;
  'heart-beat': ImageRequireSource;
  'ear-piece': ImageRequireSource;
  'play-music': ImageRequireSource;
  'setting-outline': ImageRequireSource;
  'my-location': ImageRequireSource;
  back: ImageRequireSource;
  plus: ImageRequireSource;
  add: ImageRequireSource;
  breakfast: ImageRequireSource;
  cart: ImageRequireSource;
  calendar: ImageRequireSource;
  scan: ImageRequireSource;
}
export const Icons: IconName = {
  back: require('./ic_back.png'),
  fb: require('./ic_fb.png'),
  logo: require('./ic_logo.png'),
  'arrow-back': require('./ic_arrow_back.png'),
  google: require('./ic_gg.png'),
  apple: require('./ic_apple.png'),
  location: require('./ic_location.png'),
  'right-play': require('./ic_right_play.png'),
  'left-play': require('./ic_left_play.png'),
  'close-eye': require('./ic_close_eye.png'),
  eye: require('./ic_eye.png'),
  'face-id': require('./ic_faceid.png'),
  'arrow-left': require('./ic_arrow_left.png'),
  'arrow-right': require('./ic_arrow_right.png'),
  user: require('./ic_user.png'),
  email: require('./ic_email.png'),
  lock: require('./ic_lock.png'),
  close: require('./ic_close.png'),
  cc: require('./ic_cc.png'),
  passport: require('./ic_passport.png'),
  'face-detection': require('./ic_face-detection.png'),
  home: require('./ic_home.png'),
  logout: require('./ic_logout.png'),
  flame: require('./ic_flame.png'),
  message: require('./ic_message.png'),
  bag: require('./ic_bag.png'),
  search: require('./ic_search.png'),
  settings: require('./ic_settings.png'),
  'shape-close': require('./ic_shape_close.png'),
  'white-logo': require('./ic_white_logo.png'),
  'arrow-top': require('./ic_arrow_top.png'),
  arrow_right: require('./ic_arrow_shape_right.png'),
  portfolios: require('./ic_portfolios.png'),
  more: require('./ic_more.png'),
  message_menu: require('./ic_message_menu.png'),
  home_menu: require('./ic_home_menu.png'),
  logout_menu: require('./ic_logout_menu.png'),
  settings_menu: require('./ic_settings_menu.png'),
  profile_menu: require('./ic_profile_menu.png'),
  portfolios_menu: require('./ic_portfolios_menu.png'),
  short_code: require('./ic_short_code.png'),
  page: require('./ic_page.png'),
  features: require('./ic_features.png'),
  extra_shop: require('./ic_extra_shop.png'),
  instagram: require('./ic_instagram.png'),
  twitter: require('./ic_twitter.png'),
  'outline-setting': require('./ic_outline_setting.png'),
  notification: require('./ic_notification.png'),
  phone: require('./ic_phone.png'),
  information: require('./ic_information.png'),
  'warning-mess': require('./ic_warning_mess.png'),
  option: require('./ic_option.png'),
  'small-location': require('./ic_small_location.png'),
  wishlist: require('./ic_wishlist.png'),
  order: require('./ic_order.png'),
  'credit-card': require('./ic_credit_card.png'),
  searchBottom: require('./ic_search_bottom.png'),
  filter: require('./ic_filter.png'),
  heart: require('./ic_heart.png'),
  profile: require('./ic_profile.png'),
  award: require('./ic_award.png'),
  mess: require('./ic_message.png'),
  call: require('./ic_call.png'),
  stethoscope: require('./ic_stethoscope.png'),
  personal: require('./ic_personal.png'),
  burn: require('./ic_burn.png'),
  tree: require('./ic_tree.png'),
  combined: require('./ic_combined.png'),
  doctor: require('./ic_doctor.png'),
  medicine: require('./ic_medicine.png'),
  bookmark: require('./ic_bookmark.png'),
  'heart-beat': require('./ic_heart_beat.png'),
  'ear-piece': require('./ic_ear_piece.png'),
  'cup-of-tea': require('./ic_cup_of_tea.png'),
  car: require('./ic_car.png'),
  health: require('./ic_health.png'),
  travel: require('./ic_travel.png'),
  food: require('./ic_food.png'),
  drink: require('./ic_drink.png'),
  ladder: require('./ic_ladder.png'),
  upload: require('./ic_upload.png'),
  rewind: require('./ic_rewind.png'),
  forward: require('./ic_forward.png'),
  play: require('./ic_play.png'),
  repeat: require('./ic_repeat.png'),
  pause: require('./ic_pause.png'),
  shuffle: require('./ic_shuffle.png'),
  smile: require('./ic_smile.png'),
  share: require('./ic_share.png'),
  edit: require('./ic_edit.png'),
  glueco: require('./ic_glueco.png'),
  weight: require('./ic_weight.png'),
  plus: require('./ic_plus.png'),
  add: require('./ic_add.png'),
  breakfast: require('./ic_breakfast.png'),
  'bookmark-outline': require('./ic_bookmark_outline.png'),
  'play-music': require('./ic_play_music.png'),
  'setting-outline': require('./ic_setting_outline.png'),
  'my-location': require('./ic_my_location.png'),
  cart: require('./cart.png'),
  calendar: require('./calendar.png'),
  scan: require('./scan.png'),
};
