export type RootStackParamList = {
  SplashScreen: undefined,
  Walkthroughs: undefined,
  Auth: undefined,
  Menu: undefined,
  Profile: undefined,
  News: undefined,
  Media: undefined,
  Statics: undefined,
  Dashboard: undefined,
  DashboardSummary: undefined,
  Cost: undefined,
  Scan: undefined,
  AddPerson: undefined,
  AddCost: undefined,
  SignIn: undefined,
  CreateAccount: undefined,
};
export type WalkthroughsStackParamList = {
  WalkthroughsIntro: undefined,
  Walkthroughs01: undefined,
  Walkthroughs02: undefined,
  Walkthroughs03: undefined,
  Walkthroughs04: undefined,
  Walkthroughs05: undefined,
  Walkthroughs06: undefined,
  Walkthroughs07: undefined,
  Walkthroughs08: undefined,
  Walkthroughs09: undefined,
  Walkthroughs10: undefined,
};
export type AuthStackParamList = {
  AuthIntro: undefined,
  SignIn01: undefined,
  SignIn02: undefined,
  SignIn03: undefined,
  SignUp01: undefined,
  SignUp02: undefined,
  SignUp03: undefined,
  CreateAccount: undefined,
  ForgotPassword: undefined,
  Verify: undefined,
  KYC: undefined,
  SetupInterest: undefined,
};
export type MenuStackParamList = {
  MenuIntro: undefined,
  Menu01: undefined,
  Menu02: undefined,
  Menu03: undefined,
  Menu04: undefined,
  Menu05: undefined,
  Menu06: undefined,
  Menu07: undefined,
  Menu08: undefined,
  Menu09: undefined,
  Menu10: undefined,
  Menu11: undefined,
  Menu12: undefined,
};
export type ProfileStackParamList = {
  ProfileIntro: undefined,
  Profile01: undefined,
  Profile02: undefined,
  Profile03: undefined,
  Profile04: undefined,
  Profile05: undefined,
  Profile06: undefined,
  Profile07: undefined,
  Profile08: undefined,
  Profile09: undefined,
  Profile10: undefined,
};
export type NewsStackParamList = {
  NewsIntro: undefined,
  News01: undefined,
  News02: undefined,
  News03: undefined,
  News04: undefined,
  News05: undefined,
  News06: undefined,
  News07: undefined,
  News08: undefined,
  News09: undefined,
  News10: undefined,
  News11: undefined,
  News12: undefined,
};
export type MediaStackParamList = {
  MediaIntro: undefined,
  Media01: undefined,
  Media02: undefined,
  Media03: undefined,
  Media04: undefined,
  Media05: undefined,
  Media06: undefined,
  Media07: undefined,
  Media08: undefined,
  Media09: undefined,
  Media10: undefined,
};
export type StaticsStackParamList = {
  StaticsIntro: undefined,
  Statics01: undefined,
  Statics02: undefined,
  Statics03: undefined,
  Statics04: undefined,
  Statics05: undefined,
  Statics06: undefined,
  Statics07: undefined,
  Statics08: undefined,
  Statics09: undefined,
  Statics10: undefined,
};
